apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gatekeeper-policy
policyDefaults:
  namespace: policies
  remediationAction: enforce
policies:
  - name: gatekeeper-policy
    manifests:
      - path: gatekeeper.yaml
